### PR TITLE
Update CompositeTextMapPropagator to use the default MultiPropagator from otel

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
LGTM

**Review by jkwatson — APPROVED** [review]

**Comment by jonatan-ivanov** [comment]
Thank you very much for the PR! :) We need to set-up the bot that checks the Contributors License Agreement for this repo but after that is done, I think we should merge this.

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by bogdandrutu** [comment]
köszönöm 👍

**Comment by marcingrzejszczak** [comment]
I'm not an expert on this so I don't know how to do it better but can you add one more commit to trigger the CLA bot again? Sorry :grimacing: :facepalm:

**Comment by bogdandrutu** [comment]
Usually closing and reopening the PR does the trick

**Comment by marcingrzejszczak** [comment]
Doesn't work. How about you click this one

https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=8

**Comment by marcingrzejszczak** [comment]
I think I haven't added the webhook properly. Let me double check that

**Comment by bogdandrutu** [comment]
@marcingrzejszczak suggest creating a new PR and check that the webhook works :)

**Comment by marcingrzejszczak** [comment]
yeah that's what I did and it doesn't :P I'll try to fix it, in the meantime can you check if the link works fine and that you've signed the CLA ?

**Comment by bogdandrutu** [comment]
@marcingrzejszczak discussing with the company oss committee about this, will come back soon :)

**Comment by pivotal-issuemaster** [comment]
@bogdandrutu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=8) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by marcingrzejszczak** [comment]
Ha! Finally the CLA bot works :) Thanks @trevormarshall for the help!

**Comment by pivotal-issuemaster** [comment]
@bogdandrutu Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=8)!

**Comment by bogdandrutu** [comment]
@marcingrzejszczak done

**Comment by jonatan-ivanov** [comment]
@bogdandrutu Mulţumesc! :)

**Pull request merged**
